// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SirusDbScrapper.UIDatabase {

  /// <summary>Holder for reflection information generated from test.proto</summary>
  public static partial class TestReflection {

    #region Descriptor
    /// <summary>File descriptor for test.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgp0ZXN0LnByb3RvEgVwcm90byIvChhDaGFyYWN0ZXJTdGF0c1Rlc3RSZXN1",
            "bHQSEwoLZmluYWxfc3RhdHMYASADKAEiKAoVU3RhdFdlaWdodHNUZXN0UmVz",
            "dWx0Eg8KB3dlaWdodHMYASADKAEiUQoNRHBzVGVzdFJlc3VsdBILCgNkcHMY",
            "ASABKAESCwoDdHBzGAIgASgBEgwKBGR0cHMYAyABKAESCwoDaHBzGAQgASgB",
            "EgsKA3RtaRgFIAEoASJxCg9DYXN0c1Rlc3RSZXN1bHQSMAoFY2FzdHMYASAD",
            "KAsyIS5wcm90by5DYXN0c1Rlc3RSZXN1bHQuQ2FzdHNFbnRyeRosCgpDYXN0",
            "c0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoAToCOAEi/wQKD1Rl",
            "c3RTdWl0ZVJlc3VsdBJSChdjaGFyYWN0ZXJfc3RhdHNfcmVzdWx0cxgCIAMo",
            "CzIxLnByb3RvLlRlc3RTdWl0ZVJlc3VsdC5DaGFyYWN0ZXJTdGF0c1Jlc3Vs",
            "dHNFbnRyeRJMChRzdGF0X3dlaWdodHNfcmVzdWx0cxgDIAMoCzIuLnByb3Rv",
            "LlRlc3RTdWl0ZVJlc3VsdC5TdGF0V2VpZ2h0c1Jlc3VsdHNFbnRyeRI7Cgtk",
            "cHNfcmVzdWx0cxgBIAMoCzImLnByb3RvLlRlc3RTdWl0ZVJlc3VsdC5EcHNS",
            "ZXN1bHRzRW50cnkSPwoNY2FzdHNfcmVzdWx0cxgEIAMoCzIoLnByb3RvLlRl",
            "c3RTdWl0ZVJlc3VsdC5DYXN0c1Jlc3VsdHNFbnRyeRpdChpDaGFyYWN0ZXJT",
            "dGF0c1Jlc3VsdHNFbnRyeRILCgNrZXkYASABKAkSLgoFdmFsdWUYAiABKAsy",
            "Hy5wcm90by5DaGFyYWN0ZXJTdGF0c1Rlc3RSZXN1bHQ6AjgBGlcKF1N0YXRX",
            "ZWlnaHRzUmVzdWx0c0VudHJ5EgsKA2tleRgBIAEoCRIrCgV2YWx1ZRgCIAEo",
            "CzIcLnByb3RvLlN0YXRXZWlnaHRzVGVzdFJlc3VsdDoCOAEaRwoPRHBzUmVz",
            "dWx0c0VudHJ5EgsKA2tleRgBIAEoCRIjCgV2YWx1ZRgCIAEoCzIULnByb3Rv",
            "LkRwc1Rlc3RSZXN1bHQ6AjgBGksKEUNhc3RzUmVzdWx0c0VudHJ5EgsKA2tl",
            "eRgBIAEoCRIlCgV2YWx1ZRgCIAEoCzIWLnByb3RvLkNhc3RzVGVzdFJlc3Vs",
            "dDoCOAFCHaoCGlNpcnVzRGJTY3JhcHBlci5VSURhdGFiYXNlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SirusDbScrapper.UIDatabase.CharacterStatsTestResult), global::SirusDbScrapper.UIDatabase.CharacterStatsTestResult.Parser, new[]{ "FinalStats" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SirusDbScrapper.UIDatabase.StatWeightsTestResult), global::SirusDbScrapper.UIDatabase.StatWeightsTestResult.Parser, new[]{ "Weights" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SirusDbScrapper.UIDatabase.DpsTestResult), global::SirusDbScrapper.UIDatabase.DpsTestResult.Parser, new[]{ "Dps", "Tps", "Dtps", "Hps", "Tmi" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SirusDbScrapper.UIDatabase.CastsTestResult), global::SirusDbScrapper.UIDatabase.CastsTestResult.Parser, new[]{ "Casts" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::SirusDbScrapper.UIDatabase.TestSuiteResult), global::SirusDbScrapper.UIDatabase.TestSuiteResult.Parser, new[]{ "CharacterStatsResults", "StatWeightsResults", "DpsResults", "CastsResults" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CharacterStatsTestResult : pb::IMessage<CharacterStatsTestResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CharacterStatsTestResult> _parser = new pb::MessageParser<CharacterStatsTestResult>(() => new CharacterStatsTestResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CharacterStatsTestResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SirusDbScrapper.UIDatabase.TestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharacterStatsTestResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharacterStatsTestResult(CharacterStatsTestResult other) : this() {
      finalStats_ = other.finalStats_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CharacterStatsTestResult Clone() {
      return new CharacterStatsTestResult(this);
    }

    /// <summary>Field number for the "final_stats" field.</summary>
    public const int FinalStatsFieldNumber = 1;
    private static readonly pb::FieldCodec<double> _repeated_finalStats_codec
        = pb::FieldCodec.ForDouble(10);
    private readonly pbc::RepeatedField<double> finalStats_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> FinalStats {
      get { return finalStats_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CharacterStatsTestResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CharacterStatsTestResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!finalStats_.Equals(other.finalStats_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= finalStats_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      finalStats_.WriteTo(output, _repeated_finalStats_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      finalStats_.WriteTo(ref output, _repeated_finalStats_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += finalStats_.CalculateSize(_repeated_finalStats_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CharacterStatsTestResult other) {
      if (other == null) {
        return;
      }
      finalStats_.Add(other.finalStats_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 9: {
            finalStats_.AddEntriesFrom(input, _repeated_finalStats_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 9: {
            finalStats_.AddEntriesFrom(ref input, _repeated_finalStats_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StatWeightsTestResult : pb::IMessage<StatWeightsTestResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StatWeightsTestResult> _parser = new pb::MessageParser<StatWeightsTestResult>(() => new StatWeightsTestResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<StatWeightsTestResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SirusDbScrapper.UIDatabase.TestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StatWeightsTestResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StatWeightsTestResult(StatWeightsTestResult other) : this() {
      weights_ = other.weights_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StatWeightsTestResult Clone() {
      return new StatWeightsTestResult(this);
    }

    /// <summary>Field number for the "weights" field.</summary>
    public const int WeightsFieldNumber = 1;
    private static readonly pb::FieldCodec<double> _repeated_weights_codec
        = pb::FieldCodec.ForDouble(10);
    private readonly pbc::RepeatedField<double> weights_ = new pbc::RepeatedField<double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<double> Weights {
      get { return weights_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as StatWeightsTestResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(StatWeightsTestResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!weights_.Equals(other.weights_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= weights_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      weights_.WriteTo(output, _repeated_weights_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      weights_.WriteTo(ref output, _repeated_weights_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += weights_.CalculateSize(_repeated_weights_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(StatWeightsTestResult other) {
      if (other == null) {
        return;
      }
      weights_.Add(other.weights_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 9: {
            weights_.AddEntriesFrom(input, _repeated_weights_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 9: {
            weights_.AddEntriesFrom(ref input, _repeated_weights_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DpsTestResult : pb::IMessage<DpsTestResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DpsTestResult> _parser = new pb::MessageParser<DpsTestResult>(() => new DpsTestResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DpsTestResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SirusDbScrapper.UIDatabase.TestReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DpsTestResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DpsTestResult(DpsTestResult other) : this() {
      dps_ = other.dps_;
      tps_ = other.tps_;
      dtps_ = other.dtps_;
      hps_ = other.hps_;
      tmi_ = other.tmi_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DpsTestResult Clone() {
      return new DpsTestResult(this);
    }

    /// <summary>Field number for the "dps" field.</summary>
    public const int DpsFieldNumber = 1;
    private double dps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Dps {
      get { return dps_; }
      set {
        dps_ = value;
      }
    }

    /// <summary>Field number for the "tps" field.</summary>
    public const int TpsFieldNumber = 2;
    private double tps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Tps {
      get { return tps_; }
      set {
        tps_ = value;
      }
    }

    /// <summary>Field number for the "dtps" field.</summary>
    public const int DtpsFieldNumber = 3;
    private double dtps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Dtps {
      get { return dtps_; }
      set {
        dtps_ = value;
      }
    }

    /// <summary>Field number for the "hps" field.</summary>
    public const int HpsFieldNumber = 4;
    private double hps_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Hps {
      get { return hps_; }
      set {
        hps_ = value;
      }
    }

    /// <summary>Field number for the "tmi" field.</summary>
    public const int TmiFieldNumber = 5;
    private double tmi_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Tmi {
      get { return tmi_; }
      set {
        tmi_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DpsTestResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DpsTestResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Dps, other.Dps)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Tps, other.Tps)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Dtps, other.Dtps)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Hps, other.Hps)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Tmi, other.Tmi)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Dps != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Dps);
      if (Tps != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Tps);
      if (Dtps != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Dtps);
      if (Hps != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Hps);
      if (Tmi != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Tmi);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Dps != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Dps);
      }
      if (Tps != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Tps);
      }
      if (Dtps != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Dtps);
      }
      if (Hps != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Hps);
      }
      if (Tmi != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Tmi);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Dps != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Dps);
      }
      if (Tps != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Tps);
      }
      if (Dtps != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Dtps);
      }
      if (Hps != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Hps);
      }
      if (Tmi != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Tmi);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Dps != 0D) {
        size += 1 + 8;
      }
      if (Tps != 0D) {
        size += 1 + 8;
      }
      if (Dtps != 0D) {
        size += 1 + 8;
      }
      if (Hps != 0D) {
        size += 1 + 8;
      }
      if (Tmi != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DpsTestResult other) {
      if (other == null) {
        return;
      }
      if (other.Dps != 0D) {
        Dps = other.Dps;
      }
      if (other.Tps != 0D) {
        Tps = other.Tps;
      }
      if (other.Dtps != 0D) {
        Dtps = other.Dtps;
      }
      if (other.Hps != 0D) {
        Hps = other.Hps;
      }
      if (other.Tmi != 0D) {
        Tmi = other.Tmi;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Dps = input.ReadDouble();
            break;
          }
          case 17: {
            Tps = input.ReadDouble();
            break;
          }
          case 25: {
            Dtps = input.ReadDouble();
            break;
          }
          case 33: {
            Hps = input.ReadDouble();
            break;
          }
          case 41: {
            Tmi = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Dps = input.ReadDouble();
            break;
          }
          case 17: {
            Tps = input.ReadDouble();
            break;
          }
          case 25: {
            Dtps = input.ReadDouble();
            break;
          }
          case 33: {
            Hps = input.ReadDouble();
            break;
          }
          case 41: {
            Tmi = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CastsTestResult : pb::IMessage<CastsTestResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CastsTestResult> _parser = new pb::MessageParser<CastsTestResult>(() => new CastsTestResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CastsTestResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SirusDbScrapper.UIDatabase.TestReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CastsTestResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CastsTestResult(CastsTestResult other) : this() {
      casts_ = other.casts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CastsTestResult Clone() {
      return new CastsTestResult(this);
    }

    /// <summary>Field number for the "casts" field.</summary>
    public const int CastsFieldNumber = 1;
    private static readonly pbc::MapField<string, double>.Codec _map_casts_codec
        = new pbc::MapField<string, double>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForDouble(17, 0D), 10);
    private readonly pbc::MapField<string, double> casts_ = new pbc::MapField<string, double>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, double> Casts {
      get { return casts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CastsTestResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CastsTestResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Casts.Equals(other.Casts)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Casts.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      casts_.WriteTo(output, _map_casts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      casts_.WriteTo(ref output, _map_casts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += casts_.CalculateSize(_map_casts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CastsTestResult other) {
      if (other == null) {
        return;
      }
      casts_.Add(other.casts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            casts_.AddEntriesFrom(input, _map_casts_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            casts_.AddEntriesFrom(ref input, _map_casts_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TestSuiteResult : pb::IMessage<TestSuiteResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestSuiteResult> _parser = new pb::MessageParser<TestSuiteResult>(() => new TestSuiteResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestSuiteResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SirusDbScrapper.UIDatabase.TestReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestSuiteResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestSuiteResult(TestSuiteResult other) : this() {
      characterStatsResults_ = other.characterStatsResults_.Clone();
      statWeightsResults_ = other.statWeightsResults_.Clone();
      dpsResults_ = other.dpsResults_.Clone();
      castsResults_ = other.castsResults_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestSuiteResult Clone() {
      return new TestSuiteResult(this);
    }

    /// <summary>Field number for the "character_stats_results" field.</summary>
    public const int CharacterStatsResultsFieldNumber = 2;
    private static readonly pbc::MapField<string, global::SirusDbScrapper.UIDatabase.CharacterStatsTestResult>.Codec _map_characterStatsResults_codec
        = new pbc::MapField<string, global::SirusDbScrapper.UIDatabase.CharacterStatsTestResult>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::SirusDbScrapper.UIDatabase.CharacterStatsTestResult.Parser), 18);
    private readonly pbc::MapField<string, global::SirusDbScrapper.UIDatabase.CharacterStatsTestResult> characterStatsResults_ = new pbc::MapField<string, global::SirusDbScrapper.UIDatabase.CharacterStatsTestResult>();
    /// <summary>
    /// Maps test names to their results.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::SirusDbScrapper.UIDatabase.CharacterStatsTestResult> CharacterStatsResults {
      get { return characterStatsResults_; }
    }

    /// <summary>Field number for the "stat_weights_results" field.</summary>
    public const int StatWeightsResultsFieldNumber = 3;
    private static readonly pbc::MapField<string, global::SirusDbScrapper.UIDatabase.StatWeightsTestResult>.Codec _map_statWeightsResults_codec
        = new pbc::MapField<string, global::SirusDbScrapper.UIDatabase.StatWeightsTestResult>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::SirusDbScrapper.UIDatabase.StatWeightsTestResult.Parser), 26);
    private readonly pbc::MapField<string, global::SirusDbScrapper.UIDatabase.StatWeightsTestResult> statWeightsResults_ = new pbc::MapField<string, global::SirusDbScrapper.UIDatabase.StatWeightsTestResult>();
    /// <summary>
    /// Maps test names to their results.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::SirusDbScrapper.UIDatabase.StatWeightsTestResult> StatWeightsResults {
      get { return statWeightsResults_; }
    }

    /// <summary>Field number for the "dps_results" field.</summary>
    public const int DpsResultsFieldNumber = 1;
    private static readonly pbc::MapField<string, global::SirusDbScrapper.UIDatabase.DpsTestResult>.Codec _map_dpsResults_codec
        = new pbc::MapField<string, global::SirusDbScrapper.UIDatabase.DpsTestResult>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::SirusDbScrapper.UIDatabase.DpsTestResult.Parser), 10);
    private readonly pbc::MapField<string, global::SirusDbScrapper.UIDatabase.DpsTestResult> dpsResults_ = new pbc::MapField<string, global::SirusDbScrapper.UIDatabase.DpsTestResult>();
    /// <summary>
    /// Maps test names to their results.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::SirusDbScrapper.UIDatabase.DpsTestResult> DpsResults {
      get { return dpsResults_; }
    }

    /// <summary>Field number for the "casts_results" field.</summary>
    public const int CastsResultsFieldNumber = 4;
    private static readonly pbc::MapField<string, global::SirusDbScrapper.UIDatabase.CastsTestResult>.Codec _map_castsResults_codec
        = new pbc::MapField<string, global::SirusDbScrapper.UIDatabase.CastsTestResult>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::SirusDbScrapper.UIDatabase.CastsTestResult.Parser), 34);
    private readonly pbc::MapField<string, global::SirusDbScrapper.UIDatabase.CastsTestResult> castsResults_ = new pbc::MapField<string, global::SirusDbScrapper.UIDatabase.CastsTestResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::SirusDbScrapper.UIDatabase.CastsTestResult> CastsResults {
      get { return castsResults_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestSuiteResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestSuiteResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!CharacterStatsResults.Equals(other.CharacterStatsResults)) return false;
      if (!StatWeightsResults.Equals(other.StatWeightsResults)) return false;
      if (!DpsResults.Equals(other.DpsResults)) return false;
      if (!CastsResults.Equals(other.CastsResults)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= CharacterStatsResults.GetHashCode();
      hash ^= StatWeightsResults.GetHashCode();
      hash ^= DpsResults.GetHashCode();
      hash ^= CastsResults.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dpsResults_.WriteTo(output, _map_dpsResults_codec);
      characterStatsResults_.WriteTo(output, _map_characterStatsResults_codec);
      statWeightsResults_.WriteTo(output, _map_statWeightsResults_codec);
      castsResults_.WriteTo(output, _map_castsResults_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dpsResults_.WriteTo(ref output, _map_dpsResults_codec);
      characterStatsResults_.WriteTo(ref output, _map_characterStatsResults_codec);
      statWeightsResults_.WriteTo(ref output, _map_statWeightsResults_codec);
      castsResults_.WriteTo(ref output, _map_castsResults_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += characterStatsResults_.CalculateSize(_map_characterStatsResults_codec);
      size += statWeightsResults_.CalculateSize(_map_statWeightsResults_codec);
      size += dpsResults_.CalculateSize(_map_dpsResults_codec);
      size += castsResults_.CalculateSize(_map_castsResults_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestSuiteResult other) {
      if (other == null) {
        return;
      }
      characterStatsResults_.Add(other.characterStatsResults_);
      statWeightsResults_.Add(other.statWeightsResults_);
      dpsResults_.Add(other.dpsResults_);
      castsResults_.Add(other.castsResults_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dpsResults_.AddEntriesFrom(input, _map_dpsResults_codec);
            break;
          }
          case 18: {
            characterStatsResults_.AddEntriesFrom(input, _map_characterStatsResults_codec);
            break;
          }
          case 26: {
            statWeightsResults_.AddEntriesFrom(input, _map_statWeightsResults_codec);
            break;
          }
          case 34: {
            castsResults_.AddEntriesFrom(input, _map_castsResults_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dpsResults_.AddEntriesFrom(ref input, _map_dpsResults_codec);
            break;
          }
          case 18: {
            characterStatsResults_.AddEntriesFrom(ref input, _map_characterStatsResults_codec);
            break;
          }
          case 26: {
            statWeightsResults_.AddEntriesFrom(ref input, _map_statWeightsResults_codec);
            break;
          }
          case 34: {
            castsResults_.AddEntriesFrom(ref input, _map_castsResults_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
